In [1]:
!pip install ttach


In [2]:
import wandb

In [3]:
wandb.login()


wandb: ERROR Not authenticated.  Copy a key from https://app.wandb.ai/authorize


API Key: ········


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


True

In [ ]:
!python -W ignore ../src/train.py --tags "5#att#" --base "efficientnet_b0" --image_size 224 --lr 2e-4 --epochs 200 \
--batch_size 8 --wandb 1 --path /project/


cuda
Using device: cuda
True
Tesla V100-SXM2-16GB
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
wandb!
wandb: Tracking run with wandb version 0.8.16
wandb: Wandb version 0.8.18 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Run data is saved locally in ../logs/wandb/run-20191212_210015-q3bzkomh
wandb: Syncing run 5#att#_efficientnet_b0_ft_0.0002_6
wandb: ⭐️ View project at https://app.wandb.ai/nuvard/kern
wandb: 🚀 View run at https://app.wandb.ai/nuvard/kern/runs/q3bzkomh
wandb: Run `wandb off` to turn off syncing.

==> Preparing data
==> Preparing model
Using cache found in /root/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Using cache found in /root/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Adding attention
==> Initialising sampler
=====> Loading indices
=====> Loading samples
=====> Checking distribution
=====> Assigning weights
100%|███████████████████████████████████████| 2244/2244 [05:43<00:00,  6.54it/s]
==>

100%|█████████████████████████████████████████| 121/121 [01:30<00:00,  1.33it/s]
Test set: Average loss: 0.0926, F1: 0.6350

cuda:0
wandb 1
100%|█████████████████████████████████████████| 281/281 [02:21<00:00,  1.98it/s]
[371 376 372 351 416 358]
1
Train Epoch: 22 	Loss: 0.087650    F1: 0.7385    My F1: 0.7385, AP: 0.7366
100%|█████████████████████████████████████████| 121/121 [01:19<00:00,  1.52it/s]
Test set: Average loss: 0.0871, F1: 0.6400

cuda:0
wandb 1
100%|█████████████████████████████████████████| 281/281 [02:30<00:00,  1.87it/s]
[370 395 386 396 372 325]
1
Train Epoch: 23 	Loss: 0.084223    F1: 0.7562    My F1: 0.7562, AP: 0.7547
100%|█████████████████████████████████████████| 121/121 [01:12<00:00,  1.67it/s]
Test set: Average loss: 0.0925, F1: 0.6058

cuda:0
wandb 1
100%|█████████████████████████████████████████| 281/281 [02:20<00:00,  2.00it/s]
[407 406 382 331 410 308]
1
Train Epoch: 24 	Loss: 0.084402    F1: 0.7551    My F1: 0.7551, AP: 0.7535
100%|███████████████████████

In [ ]:
!python -W ignore ../src/train.py --tags "1#squese" --base "efficientnet_b2" --image_size 260 --wandb 1 --batch_size 42 --epochs 500 --inp_size 1480

In [7]:
!python -W ignore ../src/train.py --tags "3#drop0.2" --base "resnet18" --image_size 128 --lr 1e-3 --epochs 200 \
--batch_size 8 --wandb 0

==> Preparing data
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/checkpoints/resnet18-5c106cde.pth
 17%|██████▎                               | 7.44M/44.7M [00:00<00:03, 11.6MB/s]^C
 23%|████████▊                             | 10.4M/44.7M [00:00<00:02, 15.4MB/s]
Traceback (most recent call last):
  File "../src/train.py", line 286, in <module>
    main()
  File "../src/train.py", line 284, in main
    train_loop(args)
  File "../src/train.py", line 234, in train_loop
    model, optimizer, loss = prepare_base_model(lr=LR, device=DEVICE, name=BASE, weight_decay=WD, beta_1=B1, beta_2=B2)
  File "/project/src/model.py", line 148, in prepare_base_model
    model = models.resnet18(pretrained=True)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 231, in resnet18
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 217, in _resnet
    progress=progress)
  File "/usr/l

In [ ]:
!python -W ignore ../src/train.py --tags "1#drop0.2" --base "mixnet_s" --image_size 224 --wandb 1 \
          --batch_size 42 --inp_size 1536

wandb!
wandb: Tracking run with wandb version 0.8.16
wandb: Wandb version 0.8.17 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Run data is saved locally in ../logs/wandb/run-20191204_091726-jsukwu9q
wandb: Syncing run 1#drop0.2_mixnet_s_ft_0.001_6
wandb: ⭐️ View project at https://app.wandb.ai/nuvard/kern
wandb: 🚀 View run at https://app.wandb.ai/nuvard/kern/runs/jsukwu9q
wandb: Run `wandb off` to turn off syncing.

==> Preparing data
==> Preparing model
Downloading: "https://github.com/rwightman/gen-efficientnet-pytorch/archive/master.zip" to /root/.cache/torch/hub/master.zip
Using cache found in /root/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/mixnet_s-a907afbc.pth" to /root/.cache/torch/checkpoints/mixnet_s-a907afbc.pth
GenEfficientNet(
  (conv_stem): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
  (bn1): 

==> Initialising sampler
=====> Loading indices
=====> Loading samples
=====> Checking distribution
100%|███████████████████████████████████████| 2565/2565 [06:09<00:00,  6.94it/s]
=====> Assigning weights
100%|███████████████████████████████████████| 2565/2565 [06:05<00:00,  7.01it/s]
==> Training model
wandb 1
100%|███████████████████████████████████████████| 62/62 [01:29<00:00,  1.44s/it]
1
Train Epoch: 0 	Loss: 0.025671    F1: 0.6131    My F1: 0.6131, AP: 0.6102
100%|███████████████████████████████████████████| 16/16 [00:29<00:00,  1.82s/it]

Test set: Average loss: 0.0213, F1: 0.5594

wandb 1
100%|███████████████████████████████████████████| 62/62 [01:32<00:00,  1.49s/it]
1
Train Epoch: 1 	Loss: 0.021836    F1: 0.6635    My F1: 0.6635, AP: 0.6632
100%|███████████████████████████████████████████| 16/16 [00:27<00:00,  1.73s/it]

Test set: Average loss: 0.0223, F1: 0.5581

wandb 1
100%|███████████████████████████████████████████| 62/62 [01:34<00:00,  1.53s/it]
1
Train Epoch: 2 	Loss:

100%|███████████████████████████████████████████| 16/16 [00:29<00:00,  1.85s/it]

Test set: Average loss: 0.0171, F1: 0.6092

wandb 1
100%|███████████████████████████████████████████| 62/62 [01:30<00:00,  1.46s/it]
1
Train Epoch: 73 	Loss: 0.015733    F1: 0.7704    My F1: 0.7704, AP: 0.7698
100%|███████████████████████████████████████████| 16/16 [00:28<00:00,  1.79s/it]

Test set: Average loss: 0.0176, F1: 0.5948

wandb 1
100%|███████████████████████████████████████████| 62/62 [01:30<00:00,  1.47s/it]
1
Train Epoch: 74 	Loss: 0.015645    F1: 0.7610    My F1: 0.7610, AP: 0.7609
100%|███████████████████████████████████████████| 16/16 [00:28<00:00,  1.77s/it]

Test set: Average loss: 0.0158, F1: 0.6364

wandb 1
100%|███████████████████████████████████████████| 62/62 [01:35<00:00,  1.53s/it]
1
Train Epoch: 75 	Loss: 0.014287    F1: 0.7805    My F1: 0.7805, AP: 0.7803
100%|███████████████████████████████████████████| 16/16 [00:27<00:00,  1.72s/it]

Test set: Average loss: 0.0155, F1: 0.6887

In [ ]:
!python -W ignore ../src/train.py --tags "1#drop0.2" --base "mixnet_m" --image_size 224 --wandb 1 \
          --batch_size 24 --inp_size 1536

In [ ]:
!python -W ignore ../src/train.py --tags "1#drop0.2#" --base "mnasnet_a1" --image_size 224 --wandb 1